export GIT_COMMITTER_NAME="JiaQi"
export GIT_COMMITTER_EMAIL="vipjiaqi@gmail.com"
export GIT_AUTHOR_NAME="JiaQi"
export GIT_AUTHOR_EMAIL="vipjiaqi@gmail.com"
export GIT_SSH_COMMAND="ssh -i /data/gitkey"
